[package]
name = "dice_roller"
version = "0.1.0"
authors = ["Edward Paget <ed.paget@gmail.com>"]
edition = "2018"
default-run = "dice-roller"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
rand = "0.7.3"
rustyline = "6.2.0"
serenity = "0.8"
