name: Pull Request Workflow

on:
  push:
    branches: [ main ]
    paths:
      - src/**/*.rs
      - locales/app.yml
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: [ main ]
    paths:
      - src/**/*.rs
      - locales/app.yml
      - Cargo.toml
      - Cargo.lock

env:
  CARGO_TERM_COLOR: always
  AWS_ACCESS_KEY_ID: key
  AWS_SECRET_ACCESS_KEY: secret

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "dice-roller"
    - name: Build
      run: cargo build --verbose

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "dice-roller"
    - uses: hoverkraft-tech/compose-action@v2.0.1
    - name: Run tests
      run: cargo test --verbose

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "dice-roller"
    - name: Run fmt
      run: cargo fmt -- --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "dice-roller"
    - name: Run Clippy
      run: cargo clippy -- -D warnings
