name: Terraform Pull Request Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-tf:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
